### ISSUE TITLE
sphereface2 loss

### ISSUE THREAD

**Issue by ngocson1804** [IDRnD/ReDimNet#9]
Thank you for your great work!
Could you share with me the config of sphereface2 (such as alpha, s, m, t)  that you used to train the best B2 model?

**Comment by vanIvan** [comment]
Hello! Here are the hyperparameters of sphereface2 loss (they are taken from wespeaker pipeline without change), please refer to wespeaker [loss implementation](https://github.com/wenet-e2e/wespeaker/blob/master/wespeaker/models/projections.py#L66):
```yaml
# Loss/head(projection) definition
projection_args:
  do_lm: false
  easy_margin: false
  embed_dim: 192
  lanbuda: 0.7
  margin_type: C
  project_type: sphereface2
  scale: 32.0
  t: 3
```
